# Site
repository: LuisRosado/LuisRosado.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Rosado
title: Computer Engineering
email: angel.estrada0018@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: facespics
github_username:  LuisRosado
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: LuisRosado18
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Chamba
  icon: fas fa-globe
  url: https://www.tiktok.com/@yomelapasopensand4/video/7254740206367100166
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/perfil.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Computer Engineering student about to graduate. Although I have no work experience, I have developed strong technical skills throughout my career. 
  
  My passion for technology and continuous learning motivate me to seek opportunities to grow and contribute in the field of computing.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Programming since 2010
        description: | # this will include new lines to allow paragraphs
            Throughout my career in Computer Engineering, I have worked on a variety of academic and personal projects that have strengthened my technical skills. These projects include creating web and mobile applications, solving programming challenges, and collaborating on team projects. Although I have no formal work experience, these experiences have allowed me to apply my theoretical knowledge in practical settings and develop problem-solving skills.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guadalajara
        caption: 2020 - 2023
        sub_title: Bachelor's degree in computer engineering
        quote: >
          Graduates from the University of Guadalajara (UdG) are considered excellent due to the quality of education, the experience of the professors, the available resources, and the research opportunities. Collaboration with industry and the university's reputation also contribute to the success of its graduates. However, ultimate success depends on the individual effort and skills of each graduate.
        description: | # this will include new lines to allow paragraphs
          As a graduate of the University of Guadalajara (UdG) with a degree in Computer Engineering, I have acquired a wide range of skills that prepare me to excel in the field of computing. Some of my skills include:

          -> Programming: I have experience in several programming languages, such as Java, Python and C++, which allows me to develop applications and software effectively.

          -> Algorithm Design: I can design efficient algorithms to solve computational problems optimally.

          -> Software Development: I am trained in the complete software development cycle, from planning and design to implementation and testing.

          -> Databases: I have knowledge in database design and data management using database management systems (DBMS).

          -> Networking: I understand the concepts of networks and protocols, as well as being able to configure and maintain networks effectively.

          -> Computer Security: I am aware of best practices in cybersecurity and can protect systems and data.

          -> Web Development: I have experience developing websites and web applications using technologies such as HTML, CSS and JavaScript.

          -> Artificial Intelligence and Machine Learning: I am familiar with machine learning techniques and can apply artificial intelligence to solve complex problems.

          -> Cloud Computing: I have knowledge in the use of cloud services such as AWS, Azure and Google Cloud.

          -> Project Management: I possess project management skills that allow me to carry out software development projects effectively.

          -> Problem Solving: I approach complex problems analytically and seek creative solutions.

          -> Technical Communication: I can communicate effectively, both orally and in writing, especially in project documentation.

          -> Teamwork: I collaborate effectively in multidisciplinary teams and contribute constructively to joint projects.

          -> Continuous Learning: I maintain an attitude of constant learning to stay current in a rapidly evolving field.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
