# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Angel Rosado Estrada
title: Ingeniero en computacion
email: angel.estrada0018@gmail.com
#website: https://luisrosado.github.io./

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  LuisRosado
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: Luis Angel Rosado
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links: Chamba
- title: 
  icon: fas fa-globe
  url: https://www.youtube.com/shorts/T3yBBuEbMWQ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy un estudiante en Ingeniería en Computación con una sólida base en programación y desarrollo de software. Mi educación me ha proporcionado un conocimiento sólido en áreas como <mark>algoritmos<mark>, <mark>bases de datos<mark> y <mark>seguridad informática<mark>. A pesar de mi falta de experiencia laboral formal, estoy entusiasmado por aplicar mis habilidades y aprender de manera activa en un entorno profesional. Mi pasión por la tecnología, mi disposición para asumir desafíos y mi compromiso con el crecimiento continuo me hacen un candidato motivado y dispuesto a contribuir al éxito de su organización.

content:
  - title: Projectos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pagina web para libreria
        link: https://github.com/LuisRosado/TiendaDeLibros
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Educacion # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2019 - 2024
        sub_title: Ingenieria en computacion
        quote: >
          La Universidad de Guadalajara (UdG) es reconocida por su calidad en programas de ingeniería debido a su reputación académica, profesorado cualificado y recursos tecnológicos avanzados. Sus programas de ingeniería abarcan diversas disciplinas y ofrecen oportunidades de investigación y colaboración con la industria, lo que la convierte en una opción sólida para estudiantes interesados en esta área.
        description: | # this will include new lines to allow paragraphs
          Al estudiar Ingeniería en Computación en la Universidad de Guadalajara (UdG), desarrolle habilidades en programación, diseño de algoritmos, desarrollo de software, bases de datos, redes, seguridad informática, inteligencia artificial, trabajo en equipo, gestión de proyectos y pensamiento lógico y analítico.
  - title: Sobre Mi
    layout: text
    content: | # this will include new lines to allow paragraphs
      Ademas de la ingenieria mis hobbys son:
      - Voleibol de playa
      - Gastronomia (estudie 2 años)
      - Videojuegos
      - Dibujo

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
