# Site
repository: LuisRosado/LuisRosado.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Luis Rosado
title: Computer Engineering
email: angel.estrada0018@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: facespics
github_username:  LuisRosado
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: LuisRosado18
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Chamba
  icon: fas fa-globe
  url: https://www.tiktok.com/@yomelapasopensand4/video/7254740206367100166
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/perfil.png
about_content: | # this will include new lines to allow paragraphs
I am Luis, a passionate Computer Engineering student about to complete my academic training. During my time at university, I have developed a solid base of knowledge and skills in the world of technology.

My primary focus has been programming, software development, and computer networking, areas in which I have gained deep understanding and experience. Additionally, I have a keen interest in cloud technology. Exploring the vast opportunities that cloud computing offers has been an exciting part of my educational journey. I am fascinated by the scalability, flexibility, and efficiency that cloud solutions provide, and I'm eager to delve deeper into this rapidly evolving field.

What has fascinated me most about my education is not only the concepts and theories, but the ability to apply this knowledge in real projects. Throughout my academic journey, I have participated in challenging academic and personal projects, including those that involve cloud computing. These projects have given me the opportunity to design and develop applications, solve complex problems, and experiment with innovative technological solutions in cloud environments.

I am excited for the opportunities the future has to offer after my graduation, particularly in the realm of cloud technology. I am always open to new connections and collaborations in this exciting and ever-evolving field. Thank you for taking the time to learn more about me!
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cyberchef
        link: https://github.com/LuisRosado/modularcyberchef
        quote: >
          Nutritional ChatBot.
        description: | # this will include new lines to allow paragraphs
          Comprehensive platform designed to provide personalized culinary recommendations using advanced algorithms and <mark>cloud services</mark>.
      - layout: top-middle
        title: Tienda de libros
        link: https://github.com/LuisRosado/TiendaDeLibros
        quote: >
          Site archetype for an online book store
        description: | # this will include new lines to allow paragraphs
          An archetypal website for an online book store that includes a home page with promotions, a search form, login, and sections for featured books, new releases, and reviews. The design is responsive, with interactive carousels and dynamic interactions using <mark>JavaScript</mark>, and uses modern styling with CSS and Google Fonts. Ideal as a base for a complete and functional book store.
      - layout: top-middle
        title: SpaceTravel
        link: https://github.com/LuisRosado/SpaceTravel
        quote: >
          Simple game in C
        description: | # this will include new lines to allow paragraphs
          The player controls a spaceship represented by a structure that stores coordinates, hearts (health), lives, and score. Asteroids are also structures that store coordinates.
      - layout: top-middle
        title: AI-Aspiradora
        link: https://github.com/LuisRosado/AI-Aspiradora
        quote: >
          Modular simulator to evaluate the performance of a smart vacuum cleaner
        description: | # this will include new lines to allow paragraphs
          A reinforcement learning algorithm is used so that the vacuum cleaner learns from your actions and rewards. The model is trained on the simulator and evaluated in terms of efficiency, cleanliness and obstacle avoidance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guadalajara
        caption: 2020 - 2023
        sub_title: Bachelor's degree in computer engineering
        quote: >
          Graduates from the University of Guadalajara (UdG) are considered excellent due to the quality of education, the experience of the professors, the available resources, and the research opportunities. Collaboration with industry and the university's reputation also contribute to the success of its graduates. However, ultimate success depends on the individual effort and skills of each graduate.
        description: | # this will include new lines to allow paragraphs
          As a graduate of the University of Guadalajara (UdG) with a degree in Computer Engineering, I have acquired a wide range of skills that prepare me to excel in the field of computing. Some of my skills include:

            - <mark>Programming</mark> : I have experience in several programming languages, such as Java, Python and C++, which allows me to develop applications and software effectively.

            - <mark>Algorithm Design</mark> : I can design efficient algorithms to solve computational problems optimally.

            - <mark>Software Development</mark> : I am trained in the complete software development cycle, from planning and design to implementation and testing.

            - <mark>Databases</mark> : I have knowledge in database design and data management using database management systems (DBMS).

            - <mark>Networking</mark> : I understand the concepts of networks and protocols, as well as being able to configure and maintain networks effectively.

            - <mark>Computer Security</mark> : I am aware of best practices in cybersecurity and can protect systems and data.

            - <mark>Web Development</mark> : I have experience developing websites and web applications using technologies such as HTML, CSS and JavaScript.

            - <mark>Artificial Intelligence and Machine Learning</mark> : I am familiar with machine learning techniques and can apply artificial intelligence to solve complex problems.

            - <mark>Cloud Computing</mark> : I have knowledge in the use of cloud services such as AWS, Azure and Google Cloud.

            - <mark>Project Management</mark> : I possess project management skills that allow me to carry out software development projects effectively.

            - <mark>Problem Solving</mark> : I approach complex problems analytically and seek creative solutions.

            - <mark>Technical Communication</mark> : I can communicate effectively, both orally and in writing, especially in project documentation.

            - <mark>Teamwork</mark> : I collaborate effectively in multidisciplinary teams and contribute constructively to joint projects.

            - <mark>Continuous Learning</mark> : I maintain an attitude of constant learning to stay current in a rapidly evolving field.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computing and software engineering some of my other interests and hobbies are:
      - Beach VolleyBall
      - Gaming
      - Gastronomy (I studied a 2-year diploma)
      - Design and drawing (I have a technical degree in graphic design)
      - Soccer


      Some courses and certifications

      ![Docker](images/docker.jpg "Docker")
      ![Kubernetes](images/Kubernetes.png "Kubernetes")
      ![Ic](images/Introduction to cloud.png "Ic")
      ![Cpp](images/cpp esencial.jpg "Cpp")
      ![Dp](images/Data Privacy.png "Dp")
      ![D101](images/Data science 101.png "D101")
      ![Dsm](images/Data science methodology.png "Dsm")
      ![DockerE](images/Docker Essentials A Developer Introduction.png "DockerE")
      ![Gai](images/Generative AI Fundamentals.jpg "Gai")
      ![Igai](images/Intro to generative ai.jpg "Igai")
      ![Irai](images/Intro to resposible ai.jpg "Irai")
      ![Illm](images/Introduction to large language models.jpg "Illm")
      
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
